#!/usr/bin/env sh

stashUnstagedChanges() {
  git commit --no-verify -m "[pre-commit] stashing unstaged changes"
  git stash push -u
  git reset --soft HEAD^
}

stash_count_before=$(git stash list | wc -l)

stashUnstagedChanges

stash_count_after=$(git stash list | wc -l)

if [ $? -ne 0 ]; then
    echo "Stashing unstaged changes failed!"
    exit 1
fi

git diff --name-only --cached --diff-filter=d | xargs prettier --check
if [ $? -ne 0 ]; then
    echo "Formatting files..."
    git diff --name-only --cached --diff-filter=d | xargs prettier --write
    git add .
    echo "Files formatted!"
fi

popIfPreviouslyStashed() {
  if (( stash_count_after > stash_count_before )); then
      git stash pop -q
  fi
}

npm test -- --onlyChanged --forceExit
if [ $? -ne 0 ]; then
    popIfPreviouslyStashed
    echo "Tests failed!"
    exit 1
fi

popIfPreviouslyStashed

exit 0
