#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git stash -q --keep-index --include-untracked
if [ $? -ne 0 ]; then
    echo "Stashing unstaged changes failed!"
    exit 1
fi

git diff --name-only --cached | xargs prettier --check
if [ $? -ne 0 ]; then
    echo "Files not formatted!"
    git stash pop -q
    exit 1
fi

npm test
if [ $? -ne 0 ]; then
    echo "Tests failed!"
    git stash pop -q
    exit 1
fi

git stash pop -q
if [ $? -ne 0 ]; then
    echo "Popping unstaged changes failed!"
    exit 1
fi

exit 0
